gomeria/administracion/urls.py
from django.urls import path
from . import views
from .views import ClienteCreateView, VehiculoCreateView, ProductoCreateView, PagoCreateView

app_name = 'administracion'

urlpatterns = [
    path('', views.home, name='home'),
    path('clientes/', views.ClienteListView.as_view(), name='clientes'),
    path('clientes/crear/', ClienteCreateView.as_view(), name='crear_cliente'),
    path('clientes/<int:pk>/', views.ClienteDetailView.as_view(), name='detalle_cliente'),
    path('buscar_cliente/', views.BuscarClienteView.as_view(), name='buscar_cliente'),
    
    path('crear_vehiculo/', VehiculoCreateView.as_view(), name='crear_vehiculo'),
    path('get_vehiculos/', views.GetVehiculosView.as_view(), name='get_vehiculos'),
    
    path('productos/', views.ProductoListView.as_view(), name='productos'),
    path('productos/crear', ProductoCreateView.as_view(), name='crear_producto'),
    
    path('servicios/', views.ServicioListView.as_view(), name='servicios'),
    path('servicios/crear', views.create_servicio, name='crear_servicio'),
    path('servicios/<int:servicio_id>/factura', views.factura, name='servicio_factura'),
    
    path('pagos/<int:servicio_id>/crear',views.realizar_pago , name='crear_pago'),
]

gomeria/gomeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administracion/', include(('administracion.urls'), namespace='administracion')),
]

gomeria/administracion/models.py
from django.db import models


# clases basicas

class Cliente(models.Model):
    nombre = models.CharField(max_length=200)
    ci = models.CharField(max_length=20)
    telefono = models.CharField(max_length=20)
    direccion = models.CharField(max_length=200)
    email = models.EmailField()
    
    def __str__(self):
        return self.nombre + ' - ' + self.ci

class Vehiculo(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    marca = models.CharField(max_length=200)
    modelo = models.CharField(max_length=200)
    placa = models.CharField(max_length=7)
    
    def __str__(self):
        return self.placa

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    marca = models.CharField(max_length=200)
    descipcion = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    
    def __str__(self):
        return self.nombre + ' - ' + self.marca + ' - ' + self.descipcion

# la siguiente clase es para el manejo de los servicios la cual llevara un registro de los servicios realizados en un vehiculo
class Servicio(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    descripcion = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    pagado = models.BooleanField(default=False)
    total = models.DecimalField(max_digits=6, decimal_places=2)
    productos = models.ManyToManyField(Producto, through='ServicioProducto')


class ServicioProducto(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.DecimalField(max_digits=6, decimal_places=2) # precio del producto en el momento de la venta
    precio_total = models.DecimalField(max_digits=6, decimal_places=2) # precio por la cantidad de productos vendidos
    
    
    
class Pago(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    fecha = models.DateField()
    monto = models.DecimalField(max_digits=6, decimal_places=2)

gomeria/administracion/forms.py
from django import forms
from .models import Cliente, Vehiculo, Producto, Servicio, Pago, ServicioProducto
from django.forms import formset_factory


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'ci', 'telefono', 'direccion', 'email']

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['cliente', 'marca', 'modelo', 'placa']
        widgets = {
            'cliente': forms.HiddenInput(),
        }

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'marca', 'descipcion', 'precio']

class ServicioForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), empty_label="Seleccione cliente")
    vehiculo = forms.ModelChoiceField(queryset=Vehiculo.objects.none(), empty_label=None)
    
    class Meta:
        model = Servicio
        fields = ['cliente','vehiculo', 'descripcion', 'precio', 'productos']
        

class PagoForm(forms.ModelForm):
    class Meta:
        model = Pago
        fields = ['servicio', 'fecha', 'monto']

gomeria/administracion/views.py
from django.views import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Cliente, Vehiculo, Producto, Servicio, Pago
from .forms import ClienteForm, VehiculoForm, ProductoForm, ServicioForm, PagoForm
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.db.models import Q
from django.utils import timezone
from django.shortcuts import redirect, get_object_or_404

#VISTA INICIO
def home(request):
    return render(request, 'administracion/home.html',{})

# vista lista de clientes
class ClienteListView(ListView):
    model = Cliente
    template_name = 'administracion/clientes/browse.html'
    context_object_name = 'clientes'
    
class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'administracion/clientes/create.html'
    success_url = reverse_lazy('administracion:clientes')
    

class ClienteDetailView(DetailView):
    model = Cliente
    template_name = 'administracion/clientes/detail.html'
    context_object_name = 'cliente'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vehiculo_form'] = VehiculoForm(initial={'cliente': self.object})
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = VehiculoForm(request.POST)
        
        if form.is_valid():
            form.save()
        
        return self.get(request, *args, **kwargs)
    

class BuscarClienteView(View):
    def get(self, request, *args, **kwargs):
        q = request.GET.get('q', '')
        clientes = Cliente.objects.filter(Q(nombre__icontains=q) | Q(ci__icontains=q))[:20]
        results = [{'id': cliente.id, 'text': f'{cliente.nombre}'} for cliente in clientes]
        return JsonResponse({'results': results})


class VehiculoCreateView(CreateView):
    model = Vehiculo
    form_class = VehiculoForm
    template_name = 'nombre_template.html'
    success_url = '/donde_redirigir_despues_de_crear'
    
class GetVehiculosView(View):
    def get(self, request, *args, **kwargs):
        cliente_id = request.GET.get('cliente_id')
        vehiculos = Vehiculo.objects.filter(cliente_id=cliente_id).values('id', 'placa')
        return JsonResponse(list(vehiculos), safe=False)

class ProductoListView(ListView):
    model = Producto
    template_name = 'administracion/productos/list.html'
    context_object_name = 'productos'
    
    
class ProductoCreateView(CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'administracion/productos/create.html'
    success_url = reverse_lazy('administracion:productos')


class ServicioListView(ListView):
    model = Servicio
    template_name = 'administracion/servicios/list.html'
    context_object_name = 'servicios'
    

class PagoCreateView(CreateView):
    model = Pago
    form_class = PagoForm
    template_name = 'nombre_template.html'
    success_url = '/donde_redirigir_despues_de_crear'
    
    
def create_servicio(request):
    if request.method == 'POST':
        # recoger los datos del formulario
        vehiculo_id = request.POST.get('vehiculo')
        
        vehiculo = Vehiculo.objects.get(id=vehiculo_id)
        descripcion = request.POST.get('descripcion')
        precio = request.POST.get('precio')
        productos = request.POST.getlist('producto[]')
        cantidades = request.POST.getlist('cantidad[]')
        
        # crear el servicio
        servicio = Servicio.objects.create(
            vehiculo=vehiculo,
            descripcion=descripcion,
            precio=precio,
            total=0,
            fecha=timezone.now(),
        )
        servicio.save()
        #añadir productos si existen
        if len(productos) > 0:
            for i, producto_id in enumerate(productos):
                producto = Producto.objects.get(id=producto_id)
                cantidad = cantidades[i]
                precio_total = producto.precio * int(cantidad)
                servicio.productos.add(producto, through_defaults={'cantidad': cantidad, 'precio': producto.precio, 'precio_total': precio_total})
        
        # calcular el total del servicio
        total = 0.0
        for item in servicio.productos.through.objects.filter(servicio=servicio):
            total += float(item.precio_total)
            print(item.precio_total)
            print(total)
        
        total += float(servicio.precio)
        
        # actualizar el total del servicio
        servicio.total = total
        servicio.save()
        
        # redirigir a la lista de servicios
        return redirect('administracion:servicios')
    else:
        productos = Producto.objects.all()
        return render(request, 'administracion/servicios/create.html', {
            'productos': productos,
        })
        
        
def realizar_pago(request,servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    
    if request.method == 'POST':
        monto = float(request.POST.get('monto'))
        fecha = timezone.now()
        
        #comprobar que el monto no sea mayor al total del servicio
        total_pagado = sum(pago.monto for pago in servicio.pago_set.all())
        if float(total_pagado) + monto > servicio.total:
            return render(request, 'administracion/pagos/create.html', {
                'servicio': servicio,
                'error': 'El monto ingresado es mayor al total del servicio',
            })
        else:
            pago = Pago.objects.create(
                servicio=servicio,
                monto=monto,
                fecha=fecha,
            )
            pago.save()
            #comprobar si el servicio ya fue pagado totalmente
            total_pagado = sum(pago.monto for pago in servicio.pago_set.all())
            if total_pagado == servicio.total:
                servicio.pagado = True
                servicio.save()
            
            return redirect('administracion:servicios')
    else:
        total_pagado = sum(pago.monto for pago in servicio.pago_set.all())
        faltante = servicio.total - total_pagado
        return render(request, 'administracion/pagos/create.html', {
            'servicio': servicio,
            'faltante': faltante,
        })
        

def factura(request, servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    items = servicio.productos.through.objects.filter(servicio=servicio)
    return render(request, 'administracion/servicios/factura.html', {
        'servicio': servicio,
        'items': items,
    })

gomeria/administracion/templates/administracion/productos/create.html
{% extends "administracion/base/base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <h4 class="mb-3">Crear producto</h4>
        <div class="row">
            <div class="col-12 col-md-8">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'administracion:crear_producto' %}" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="d-flex justify-content-end">
                                <input type="submit" value="Crear producto" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
{% endblock %}
{% block css %}
    <style>
        label {
            display: block;
        }
        input[type="text"], input[type="email"], input[type="password"]{
            width: 100%;
            padding: 5px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        img{
            width: 100%;
            height: 100%;
        }
        .errorlist li{
            color: red;
        }
    </style>
{% endblock css %}

gomeria/administracion/templates/administracion/productos/list.html
{% extends "administracion/base/base.html" %}

{% block content %}
<h1>Productos</h1>
<div class="row">
    <div class="col">
        <a href="{% url 'administracion:crear_producto' %}" class="btn btn-primary">Crear Producto</a>
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Marca</th>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for producto in productos %}
                            <tr>
                                <td>{{ producto.nombre }}</td>
                                <td>{{ producto.marca }}</td>
                                <td>{{ producto.descipcion }}</td>
                                <td>{{ producto.precio }} Bs</td>
                                <td>
                                    {% comment %} <a href="{% url 'administracion:producto_detalles' producto.id %}" class="btn btn-info">Detalles</a> {% endcomment %}
                                    <a href="" class="btn btn-warning">Editar</a>
                                    <a href="" class="btn btn-danger">Eliminar</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}