gomeria/administracion/urls.py
from django.urls import path
from . import views
from .views import ClienteCreateView, VehiculoCreateView, ProductoCreateView, PagoCreateView

app_name = 'administracion'

urlpatterns = [
    path('', views.home, name='home'),
    path('clientes/', views.ClienteListView.as_view(), name='clientes'),
    path('clientes/crear/', ClienteCreateView.as_view(), name='crear_cliente'),
    path('clientes/<int:pk>/', views.ClienteDetailView.as_view(), name='detalle_cliente'),
    path('buscar_cliente/', views.BuscarClienteView.as_view(), name='buscar_cliente'),
    
    path('crear_vehiculo/', VehiculoCreateView.as_view(), name='crear_vehiculo'),
    path('get_vehiculos/', views.GetVehiculosView.as_view(), name='get_vehiculos'),
    
    path('productos/', views.ProductoListView.as_view(), name='productos'),
    path('productos/crear', ProductoCreateView.as_view(), name='crear_producto'),
    
    path('servicios/', views.ServicioListView.as_view(), name='servicios'),
    path('servicios/crear', views.create_servicio, name='crear_servicio'),
    path('servicios/<int:servicio_id>/factura', views.factura, name='servicio_factura'),
    
    path('pagos/<int:servicio_id>/crear',views.realizar_pago , name='crear_pago'),
]

gomeria/gomeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administracion/', include(('administracion.urls'), namespace='administracion')),
]

gomeria/administracion/models.py
from django.db import models


# clases basicas

class Cliente(models.Model):
    nombre = models.CharField(max_length=200)
    ci = models.CharField(max_length=20)
    telefono = models.CharField(max_length=20)
    direccion = models.CharField(max_length=200)
    email = models.EmailField()
    
    def __str__(self):
        return self.nombre + ' - ' + self.ci

class Vehiculo(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    marca = models.CharField(max_length=200)
    modelo = models.CharField(max_length=200)
    placa = models.CharField(max_length=7)
    
    def __str__(self):
        return self.placa

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    marca = models.CharField(max_length=200)
    descipcion = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    
    def __str__(self):
        return self.nombre + ' - ' + self.marca + ' - ' + self.descipcion

# la siguiente clase es para el manejo de los servicios la cual llevara un registro de los servicios realizados en un vehiculo
class Servicio(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    descripcion = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    pagado = models.BooleanField(default=False)
    total = models.DecimalField(max_digits=6, decimal_places=2)
    productos = models.ManyToManyField(Producto, through='ServicioProducto')


class ServicioProducto(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    precio = models.DecimalField(max_digits=6, decimal_places=2) # precio del producto en el momento de la venta
    precio_total = models.DecimalField(max_digits=6, decimal_places=2) # precio por la cantidad de productos vendidos
    
    
    
class Pago(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    fecha = models.DateField()
    monto = models.DecimalField(max_digits=6, decimal_places=2)

gomeria/administracion/forms.py
from django import forms
from .models import Cliente, Vehiculo, Producto, Servicio, Pago, ServicioProducto
from django.forms import formset_factory


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'ci', 'telefono', 'direccion', 'email']

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['cliente', 'marca', 'modelo', 'placa']
        widgets = {
            'cliente': forms.HiddenInput(),
        }

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'marca', 'descipcion', 'precio']

class ServicioForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), empty_label="Seleccione cliente")
    vehiculo = forms.ModelChoiceField(queryset=Vehiculo.objects.none(), empty_label=None)
    
    class Meta:
        model = Servicio
        fields = ['cliente','vehiculo', 'descripcion', 'precio', 'productos']
        

class PagoForm(forms.ModelForm):
    class Meta:
        model = Pago
        fields = ['servicio', 'fecha', 'monto']

gomeria/administracion/views.py
from django.views import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Cliente, Vehiculo, Producto, Servicio, Pago
from .forms import ClienteForm, VehiculoForm, ProductoForm, ServicioForm, PagoForm
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.db.models import Q
from django.utils import timezone
from django.shortcuts import redirect, get_object_or_404

#VISTA INICIO
def home(request):
    return render(request, 'administracion/home.html',{})

# vista lista de clientes
class ClienteListView(ListView):
    model = Cliente
    template_name = 'administracion/clientes/browse.html'
    context_object_name = 'clientes'
    
class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'administracion/clientes/create.html'
    success_url = reverse_lazy('administracion:clientes')
    

class ClienteDetailView(DetailView):
    model = Cliente
    template_name = 'administracion/clientes/detail.html'
    context_object_name = 'cliente'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vehiculo_form'] = VehiculoForm(initial={'cliente': self.object})
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = VehiculoForm(request.POST)
        
        if form.is_valid():
            form.save()
        
        return self.get(request, *args, **kwargs)
    

class BuscarClienteView(View):
    def get(self, request, *args, **kwargs):
        q = request.GET.get('q', '')
        clientes = Cliente.objects.filter(Q(nombre__icontains=q) | Q(ci__icontains=q))[:20]
        results = [{'id': cliente.id, 'text': f'{cliente.nombre}'} for cliente in clientes]
        return JsonResponse({'results': results})


class VehiculoCreateView(CreateView):
    model = Vehiculo
    form_class = VehiculoForm
    template_name = 'nombre_template.html'
    success_url = '/donde_redirigir_despues_de_crear'
    
class GetVehiculosView(View):
    def get(self, request, *args, **kwargs):
        cliente_id = request.GET.get('cliente_id')
        vehiculos = Vehiculo.objects.filter(cliente_id=cliente_id).values('id', 'placa')
        return JsonResponse(list(vehiculos), safe=False)

class ProductoListView(ListView):
    model = Producto
    template_name = 'administracion/productos/list.html'
    context_object_name = 'productos'
    
    
class ProductoCreateView(CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'administracion/productos/create.html'
    success_url = reverse_lazy('administracion:productos')


class ServicioListView(ListView):
    model = Servicio
    template_name = 'administracion/servicios/list.html'
    context_object_name = 'servicios'
    

class PagoCreateView(CreateView):
    model = Pago
    form_class = PagoForm
    template_name = 'nombre_template.html'
    success_url = '/donde_redirigir_despues_de_crear'
    
    
def create_servicio(request):
    if request.method == 'POST':
        # recoger los datos del formulario
        vehiculo_id = request.POST.get('vehiculo')
        
        vehiculo = Vehiculo.objects.get(id=vehiculo_id)
        descripcion = request.POST.get('descripcion')
        precio = request.POST.get('precio')
        productos = request.POST.getlist('producto[]')
        cantidades = request.POST.getlist('cantidad[]')
        
        # crear el servicio
        servicio = Servicio.objects.create(
            vehiculo=vehiculo,
            descripcion=descripcion,
            precio=precio,
            total=0,
            fecha=timezone.now(),
        )
        servicio.save()
        #añadir productos si existen
        if len(productos) > 0:
            for i, producto_id in enumerate(productos):
                producto = Producto.objects.get(id=producto_id)
                cantidad = cantidades[i]
                precio_total = producto.precio * int(cantidad)
                servicio.productos.add(producto, through_defaults={'cantidad': cantidad, 'precio': producto.precio, 'precio_total': precio_total})
        
        # calcular el total del servicio
        total = 0.0
        for item in servicio.productos.through.objects.filter(servicio=servicio):
            total += float(item.precio_total)
            print(item.precio_total)
            print(total)
        
        total += float(servicio.precio)
        
        # actualizar el total del servicio
        servicio.total = total
        servicio.save()
        
        # redirigir a la lista de servicios
        return redirect('administracion:servicios')
    else:
        productos = Producto.objects.all()
        return render(request, 'administracion/servicios/create.html', {
            'productos': productos,
        })
        
        
def realizar_pago(request,servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    
    if request.method == 'POST':
        monto = float(request.POST.get('monto'))
        fecha = timezone.now()
        
        #comprobar que el monto no sea mayor al total del servicio
        total_pagado = sum(pago.monto for pago in servicio.pago_set.all())
        if float(total_pagado) + monto > servicio.total:
            return render(request, 'administracion/pagos/create.html', {
                'servicio': servicio,
                'error': 'El monto ingresado es mayor al total del servicio',
            })
        else:
            pago = Pago.objects.create(
                servicio=servicio,
                monto=monto,
                fecha=fecha,
            )
            pago.save()
            #comprobar si el servicio ya fue pagado totalmente
            total_pagado = sum(pago.monto for pago in servicio.pago_set.all())
            if total_pagado == servicio.total:
                servicio.pagado = True
                servicio.save()
            
            return redirect('administracion:servicios')
    else:
        total_pagado = sum(pago.monto for pago in servicio.pago_set.all())
        faltante = servicio.total - total_pagado
        return render(request, 'administracion/pagos/create.html', {
            'servicio': servicio,
            'faltante': faltante,
        })
        

def factura(request, servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    items = servicio.productos.through.objects.filter(servicio=servicio)
    return render(request, 'administracion/servicios/factura.html', {
        'servicio': servicio,
        'items': items,
    })

gomeria/administracion/templates/administracion/servicios/create.html
{% extends "administracion/base/base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <h4 class="mb-3">Registrar Servicio</h4>
        <div class="card">
            <div class="card-body">
                <form action="{% url 'administracion:crear_servicio' %}" method="post">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col">
                            <label for="cliente">Cliente:</label>
                            <select id="id_cliente" name="cliente" required>
                                <!-- Las opciones se cargarán dinámicamente con Select2 -->
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <label for="vehiculo">Vehiculo:</label>
                            <select id="id_vehiculo" name="vehiculo" required>
                                <!-- Las opciones se cargarán dinámicamente con Select2 -->
                            </select>
                        </div>
                        <div class="col">
                            <label for="fecha">Fecha:</label>
                            <p id="fecha"></p>
                            <script>
                            var fecha = new Date();
                            var dia = String(fecha.getDate()).padStart(2, '0');
                            var mes = String(fecha.getMonth() + 1).padStart(2, '0'); //Los meses en JavaScript empiezan en 0
                            var ano = fecha.getFullYear();
                            document.getElementById('fecha').textContent = dia + '/' + mes + '/' + ano;
                            </script>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="descripcion">Descripcion:</label>
                            <input type="text" name="descripcion" id="descripcion" placeholder="Descripcion" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="precio">Precio:</label>
                            <input type="number" name="precio" id="precio" placeholder="Precio" required>
                        </div>
                    </div>
                    <hr>
                    <div id="productoContainer">
                        <!-- Las filas de productos se agregarán aquí -->
                    </div>
                    
                    <button id="addProducto" type="button" class="btn btn-success">Agregar producto</button>
                    <button id="removeProducto" type="button" class="btn btn-danger">Eliminar Ultimo</button>
                    <hr>
                    <div class="mt-3 d-flex justify-content-end">
                        <input type="submit" value="Crear Servicio" class="btn btn-primary">
                    </div>
                    
                </form>
            </div>
        </div>
        
        
    </div>
{% endblock %}
{% block css %}
    <style>
        label {
            display: block;
        }
        input[type="text"], input[type="email"], input[type="password"]{
            width: 100%;
            padding: 5px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        input[type="number"]{
            width: 100%;
            padding: 5px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        select{
            width: 100%;
            height: 35px;
            padding: 5px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }
        img{
            width: 100%;
            height: 100%;
        }
        .errorlist{
            list-style: none;
        }
        .errorlist li{
            margin: 0;
            padding: 5px;
            color: red;
            background-color: #f8d7da;
            border-color: #f5c6cb;
            border-radius: 5px;
        }
    </style>
{% endblock css %}
{% block js %}
<script>
    $(document).ready(function() {
        $('#id_cliente').select2({
            ajax: {
                url: '{% url "administracion:buscar_cliente" %}',
                dataType: 'json'
            },
            minimumInputLength: 2,
            placeholder: 'Seleccione un cliente',
            language: {
                noResults: function() {
                    return "No hay resultado";
                },
                searching: function() {
                    return "Buscando..";
                },
                inputTooShort: function(args) {
                    var remainingChars = args.minimum - args.input.length;
                    var message = 'Por favor ingrese ' + remainingChars + ' o más caracteres';

                    return message;
                }
            }
        });
    });
</script>


<script>
$(document).ready(function() {
    $('#id_vehiculo').empty();

    $('#id_cliente').change(function() {
        var cliente_id = $(this).val();
        $.ajax({
            url: "{% url 'administracion:get_vehiculos' %}",
            data: {
                'cliente_id': cliente_id
            },
            dataType: 'json',
            success: function(data) {
                var select = $('#id_vehiculo');
                select.empty();
                $.each(data, function(index, value) {
                    select.append('<option value="' + value.id + '">' + value.placa + '</option>');
                });
            }
        });
    });
});
</script>
<script>
    document.getElementById('addProducto').addEventListener('click', function() {
        var container = document.getElementById('productoContainer');
    
        // Crea una nueva fila
        var row = document.createElement('div');
        row.className = 'row mb-3';
    
        // Crea la columna del producto
        var colProducto = document.createElement('div');
        colProducto.className = 'col';
        colProducto.innerHTML = `
            <label for="producto">Producto:</label>
            <select id="id_producto" name="producto[]" required>
                <option value="">Seleccione un producto</option>
                {% for producto in productos %}
                    <option value="{{ producto.id }}">{{ producto.nombre }}</option>
                {% endfor %}
            </select>
        `;
    
        // Crea la columna de la cantidad
        var colCantidad = document.createElement('div');
        colCantidad.className = 'col';
        colCantidad.innerHTML = `
            <label for="cantidad">Cantidad:</label>
            <input type="number" name="cantidad[]" id="cantidad" placeholder="Cantidad" required>
        `;
    
        // Añade las columnas a la fila
        row.appendChild(colProducto);
        row.appendChild(colCantidad);
    
        // Añade la fila al contenedor
        container.appendChild(row);
    });
    
    document.getElementById('removeProducto').addEventListener('click', function() {
        var container = document.getElementById('productoContainer');
        if (container.children.length > 0) {
            // Elimina la última fila
            container.removeChild(container.lastChild);
        }
    });
    </script>
{% endblock js %}

gomeria/administracion/templates/administracion/servicios/factura.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Imprimir factura</title>
    <style>
        .opt-print{
            display: flex;
            justify-content: end;
        }
        .opt-print button{
            padding: 10px;
            margin: 10px;
            border: 1px solid #000;
            border-radius: 5px;
            cursor: pointer;
        }
        
        //stilos para quitar el link de la pagina el titulo y fecha
        @page 
        {
            size:  auto;   /* auto es el valor inicial */
            margin: 0mm;  /* afecta el margen en la configuración de impresión */
        }
        body{
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
            font-size: 1rem;
            min-width: 400px;
            {% comment %} box-shadow: 0 0 20px rgba(0, 0, 0, 0.15); {% endcomment %}
        }
        
        table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }
        
        table th,
        table td {
            padding: 12px 15px;
            border: 1px solid rgba(0, 0, 0, 0.15);;
        }
        table .text-right{
            text-align: right;
        }
        
        table tbody tr {
            border-bottom: 1px solid #dddddd;
        }
        
        table tbody tr:nth-of-type(even) {
            background-color: #f3f3f3;
        }
        
        table tbody tr:last-of-type {
            border-bottom: 2px solid #009879;
        }
        .container{
            width: 80%;
            margin: 0 auto;
        }
        @media print{
            .opt-print{
                display: none;
            }
            .container{
                width: 100%;
                margin: 0 auto;
            }
        }
        h1{
            text-align: right;
        }
    </style>

</head>
<body>
    <div class="opt-print">
        <button onclick="window.close()">Cancelar</button>

        <button onclick="window.print()">Imprimir</button>
    </div>

    <div class="container">
        <h1>Factura: AND-{{servicio.id}}</h1>
        <h2>Fecha: {{ servicio.fecha|date:"d/m/Y" }}</h2>
        <h2>Cliente: {{servicio.vehiculo.cliente.nombre}}</h2>

        <table>
            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{servicio.descripcion}}</td>
                    <td class="text-right">1</td>
                    <td class="text-right">{{servicio.precio}}</td>
                    <td class="text-right">{{servicio.precio}}</td>
                </tr>
                {% for item in items %}
                    <tr>
                        <td>{{item.producto.nombre}}</td>
                        <td class="text-right">{{item.cantidad}}</td>
                        <td class="text-right">{{item.producto.precio}}</td>
                        <td class="text-right">{{item.precio_total}}</td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3"> <strong>Total</strong> </td>
                    <td class="text-right">{{servicio.total}}</td>
                </tr>
            </tfoot>
        </table>
    </div>

    <script>
        document.body.addEventListener('keypress', function(e) {
            switch (e.key) {
                case 'Enter':
                    window.print();
                    break;
                case 'Escape':
                    window.close();
                default:
                    break;
            }
        });
    </script>   
</body>
</html>

gomeria/administracion/templates/administracion/servicios/list.html
{% extends "administracion/base/base.html" %}

{% block title %}Vista lista de clientes{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="d-flex gap-3 aling-items-center">
            <h2>Servicios realizados</h2>
            <div>
                <a href="{% url 'administracion:crear_servicio' %}" class="btn btn-primary">Registrar nuevo servicio</a>
            </div>
        </div>
        <div class="card">
            <div class="card-body table-responsive">
                <div class="row">
                    <div class="col-12">
                        
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>Vehículo</th>
                                    <th>Fecha</th>
                                    <th>Descripción</th>
                                    <th>Total</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for servicio in servicios %}
                                    <tr>
                                        <td>{{ servicio.vehiculo.cliente.nombre }}</td>
                                        <td>{{ servicio.vehiculo.placa }}</td>
                                        <td>{{ servicio.fecha }}</td>
                                        <td>{{ servicio.descripcion }}</td>
                                        <td>{{ servicio.precio }}</td>
                                        <td>{{ servicio.total }}</td>
                                        <td>
                                            {% if servicio.pagado %}
                                                <a href="{% url "administracion:servicio_factura" servicio.id %}" class="btn btn-success" target="_blank">Factura</a>
                                            {% else %}
                                                <a href="{% url "administracion:crear_pago" servicio.id %}" class="btn btn-warning" >Pagar</a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}